// <auto-generated />
using System;
using Auction_Bidding.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auction_Bidding.Web.Migrations
{
    [DbContext(typeof(AuctionBiddingContext))]
    [Migration("20200820161350_AddDatabase")]
    partial class AddDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction_Bidding.Web.Data.Entities.Auction", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuctionCoverPhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuctionEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuctionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AuctionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AuctionStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionID");

                    b.ToTable("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
